apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bank-of-anthos

resources:
- ../../base
- ../../optional/ingress/nginx-ingress.yaml
- ../../optional/monitoring/servicemonitor.yaml
- ../../optional/auth/oidc-config.yaml

patchesStrategicMerge:
- production-patches.yaml

configMapGenerator:
- name: bank-of-anthos-config
  behavior: merge
  literals:
  - LOG_LEVEL=INFO
  - METRICS_ENABLED=true
  - TRACING_ENABLED=true
  - AUTH_ENABLED=true
  - AUTH_TYPE=oidc

secretGenerator:
- name: database-credentials
  behavior: replace
  literals:
  - accounts_db_uri=postgresql://username:password@external-db.example.com:5432/accounts
  - ledger_db_uri=postgresql://username:password@external-db.example.com:5432/ledger

replicas:
- name: frontend
  count: 3

images:
- name: frontend
  newTag: v0.6.7