apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bank-of-anthos

resources:
- ../../base
- ../../optional/ingress/nginx-ingress.yaml
- ../../optional/monitoring/servicemonitor.yaml

configMapGenerator:
- name: bank-of-anthos-config
  behavior: merge
  literals:
  - METRICS_ENABLED=true
  - AUTH_ENABLED=false
  - BANK_NAME=Homelab Bank
  - LOG_LEVEL=INFO

patchesStrategicMerge:
- ingress-patch.yaml

replicas:
- name: frontend
  count: 1